spring.application.name=RealTime-KOT-System

# PostgreSQL DB connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/realtime-kot-system
spring.datasource.username=postgres
spring.datasource.password=2004
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
